export default {
    FETCH_POSTS: "FETCH_POSTS",
    ON_POSTS_FETCH_SUCCESS: "ON_POSTS_FETCH_SUCCESS",
    ON_LIKE_DISLIKE_POST: "ON_LIKE_DISLIKE_POST",
    SET_POST_LIKE_DETAILS: "SET_POST_LIKE_DETAILS",
    ON_ADD_COMMENT_SUCCESS: "ON_ADD_COMMENT_SUCCESS",
    ON_DELETE_COMMENT_SUCCESS: "ON_DELETE_COMMENT_SUCCESS",
    ADD_NEW_FEED: "ADD_NEW_FEED"
};