export default {
    FETCH_USER_POSTS: "FETCH_USER_POSTS",
    ON_POST_FETCH_SUCCESS: "ON_POST_FETCH_SUCCESS",
    RESET_PROFILE_STATE: "RESET_PROFILE_STATE",
    SET_FOLLOW_STATUS: "SET_FOLLOW_STATUS"
}